### ISSUE TITLE
Water Issue

### ISSUE THREAD

**Issue by chadf-github** [hiisuuii/gmod-hologramtool#1]
Unsure if this can be fixed/needs to be fixed but this happens when you go in some water 
https://img.chadf.co.uk/img/0tHG.png

**Comment by hiisuuii** [comment]
Figured out a fix but it's a bit of a hack and doesn't look great and has some other issues. Essentially, I'm telling the renderer that if you are more than half submerged, to completely ignore depth and render the player on top of everything else. While this does get the hologram effect to work if the player is partially submerged, it _also_ means that if the player in water happens to be underground or behind a wall, you can see them through it. See: https://gyazo.com/7961863352ecb0a2e7269d04edf502ea

While I would like for the hologram effect to work underwater and if the player is partially submerged, I'd like to avoid adding a wallhack. For right now I can't seem to find a way to make it work while the player irs partially submerged without inadvertently adding a wallhack, so the better option seems to be just to just basically leave it as is. I'll reopen this if I can figure out a way without adding a wallhack, though.
